version: "3.2"
services:
    mongo:
        image: mongo:4.4.4
        container_name: uploaderdb
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ~/projects/uploads/mongodb-uploader:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example